apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ug4xsh3cw-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/ug4xsh3cw-java-quarkus